error: Audio policy no longer supports legacy .conf configuration format
frameworks/av/services/audiopolicy/managerdefault/AudioPolicyManager.cpp:4305:2: error: Audio policy no longer supports legacy .conf configuration format
#error Audio policy no longer supports legacy .conf configuration format